[package]
name = "auth-required-game"
description = "Authorisation Required - an interactive fiction puzzle game"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28.1"
egui_extras = "0.28.1"
env_logger = "0.11.5"
log = "0.4.22"
